### ISSUE TITLE
No C header file in repo?

### ISSUE THREAD

**Issue by leehambley** [M1Sports20/base16-c_header#1]
Title says it all :) did you forget a push? Happy New Year 👍

**Comment by M1Sports20** [comment]
Do people in the base16 projects usually check in the generated files?  I checked and everything is there for the builders to generate the c_header.

**Comment by leehambley** [comment]
I didn't know I needed to go get a PHP project running to use your generator. Without the knowledge that there's a whole ecosystem of tools I'd need to gen the header file, I was pretty confused. Thanks for the clarification via letting me know that the files here aren't a complete solutoin.
